# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b5eb504e4ea78a87a315dc891dc3302821cf0d74159862bc4c2b9875f6a8744f99e830af56115a68ec2b40caab0d32734f230e43d1da1d3a64bf208692df41

test:
  secret_key_base: 1e20a58046fcae6a7f1f67840a39f39f7f40763a4d366e3fa68035b4c0f1c511849e14ed4f19bc4d4a2f3596e562c2e333cf156a23d348b80166417f6d8b4fb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
